routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',function(){
    
    return redirect('/browse');
});
Route::group(['prefix'=>'browse'], function(){
    Route::get('/','BarangController@browse')->name('browse');
    Route::get('/{id}','BarangController@select')->name('browse.select');
});

Route::group(['middleware' => ['auth', 'web']], function (){
    Route::resource('barang','BarangController', ['parameters' => [
        'barang' => 'id']]);
    
    
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
    Route::group(['prefix'=>'ongkir'], function(){
        Route::get('/city','CartController@getCity')->name('ongkir.city');
        Route::get('/province','CartController@getProvince')->name('ongkir.provinsi');
        Route::post('/','CartController@getOngkir')->name('ongkir.get');
    });
    
    Route::group(['prefix'=>'cart'], function (){
        Route::get('/','CartController@index')->name('cart.index');
        Route::post('/','CartController@add')->name('cart.add');
        Route::post('/{id}','CartController@delete')->name('cart.delete');
        
    });
    Route::post('/checkout','CartController@checkout')->name('cart.checkout');
    
    Route::group(['prefix'=>'order'], function(){
        Route::post('/','OrderController@create')->name('order.create');
        Route::get('/','OrderController@myOrder')->name('order.index');
        Route::get('/getOrder','OrderController@getOrder')->name('order.getOrder');
        Route::get('/invoice/{id}','OrderController@invoice')->name('order.invoice');
        Route::post('/paid','OrderController@paid')->name('order.paid');
        Route::get('/get','OrderController@get')->name('order.get');
        
        
    });
});




Auth::routes();

app/Models/Barang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    //
    protected $table='barang';

    public $timestamps=true;

    protected $fillable=[
        'kode_barang','nama_barang',
        'stock','harga','gambar','created_at','updated_at'
    ];
}

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Barang;
use Carbon\Carbon;
class BarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data=Barang::paginate(10);
        //dd($data);
        return view('barang.index')->with('data',$data);
        //return view('barang.index')->with('data',$data);
    }

    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        
        if($request->hasFile('gambar_barang')){
            $file=$request->file('gambar_barang');
            $uploaded=Carbon::now();
            $extension=$file->getClientOriginalExtension();
            $filename=sha1($uploaded).'.'.$extension;
            
            $file->move('storage/app/public/',$filename);
            
            $data=[
                'kode_barang'=>$request->kd_barang,
                'nama_barang'=>$request->nama_barang,
                'stock'=>$request->stock_barang,
                'harga'=>$request->harga_barang,
                'gambar'=>$filename,
                'berat'=>$request->berat,
                'description'=>$request->description,
                'created_at'=>Carbon::now()
            ];
            Barang::insert($data);
            return redirect()->back();
        }
        else{
            dd($request->hasFile('gambar_barang'));
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the data for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $data=Barang::find($id);
        return view('barang.edit')->with('data',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
       dd($request->all());
        $data=[];
        if($request->hasFile('gambar_barang')){
            $file=$request->file('gambar_barang');
            $uploaded=Carbon::now();
            $extension=$file->getClientOriginalExtension();
            $filename=sha1($uploaded).'.'.$extension;
            
            $file->move('storage/app/public/',$filename);
            
            $data=[
                
                'nama_barang'=>$request->nama_barang,
                'stock'=>$request->stock_barang,
                'harga'=>$request->harga_barang,
                'gambar'=>$filename,
                'description'=>$request->description,
                'berat'=>$request->berat,
                'updated_at'=>Carbon::now()
            ];
        }
        else{
            $data=[
                'nama_barang'=>$request->nama_barang,
                'stock'=>$request->stock_barang,
                'harga'=>$request->harga_barang,
                'description'=>$request->description,
                'updated_at'=>Carbon::now()
            ];
        }
            Barang::where('id',$id)->update($data);
            return redirect('/barang');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Barang::where('id',$id)->delete();
        return redirect('/barang');
    }

    

    public function browse()
    {
        $data=Barang::paginate(10);
       
        return view('barang.browse')->with('data',$data);
    }

    public function select($id)
    {
        $data=Barang::find($id);
        return view('barang.select')->with('data',$data);
    }
}

resources/views/barang/browse.blade.php
@extends('layouts.master')

@section('content')

<div class="clearfix"></div>
<div class="row">
<div class="col-md-12">
<div class="x_panel">
<div class="x_title">
    <div class="x_content">
            <div class="row"><br>
                   @foreach ($data as $d)
                   <div class="col-md-55">
                        <div class="thumbnail">
                        <div class="image view view-first">
                        <img style="width: 100%; display: block;" src="{{asset('storage/app/public/'.$d->gambar)}}" alt="image" />
                        <div class="mask">
                       
                        <div class="tools tools-bottom">
                        <a href="{{route('browse.select',$d->id)}}"><i class="fa fa-plus"></i></a>
                        
                        </div>
                        </div>
                        </div>
                        <div class="caption">
                                <p>Rp <strong>{{number_format($d->harga,2,',','.')}}</strong>
                                </p>
                            <p>{{$d->nama_barang}}</p>
                            
                                </div>

                        </div>
                        </div>
                   @endforeach
                    
            </div>
    </div>
    </div>
</div>
</div>
</div>
</div>


@endsection

resources/views/barang/cart.blade.php
@extends('layouts.master')

@section('content')

          <div class="clearfix"></div>
          <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="x_panel">
                    <div class="x_title">
                      <h2>Data<small>Barang</small></h2>
                      
                      <div class="clearfix"></div>
                    </div>
                    <form action="{{route('cart.checkout')}}" method="post">
                    <div class="x_content">
                      <div style="overflow-x:auto">
                            <div class="row">
                            
                             
                                    <div class="col-sm-3 mail_list_column">
                                    
                                   <br>
                                    <a href="#">
                                            <div class="mail_list">
                                            
                                            <div class="right">
                                                {{ csrf_field() }}
                      <div class="" style="width:200px">
                      <div class="form-group">
                        <label for="heard">Kota Asal</label>
                      <select id="kota_asal" name="kota_asal" class="form-control js-example-basic-single" required>
                        
                      </select>
                      </div>
                
                      <div class="form-group">
                      <label for="heard">Provinsi Tujuan</label>
                      <select id="prov_tujuan" name="provinsi_tujuan" class="form-control js-example-basic-single" required>
                      
                      </select>
                      </div>
                
                      <div class="form-group">
                      <label for="heard">Kota Tujuan</label>
                      <select id="kota_tujuan" name="kota_tujuan" class="form-control js-example-basic-single" required>
                      
                      </select>
                      </div>
                
                      <div class="form-group">
                      <label for="heard">Kurir</label>
                      <select id="kurir" name="kurir" class="form-control js-example-basic-single" required>
                        <option value="jne">JNE</option>
                              <option value="tiki">TIKI</option>
                              <option value="pos">POS INDONESIA</option>
                      </select>
                      </div>
                      
                      
                        
                        Berat Total : {{$berat}} gram.
                        
                        <div class="form-group">
                          Total Ongkir : 
                        </div>
                      <br>
                      <div class="form-group">
                        
                        <button id="compose" class="btn btn-sm btn-success btn-block" type="submit">LANJUT KE CHECKOUT</button>
                        
                      </div>
                    </form> 
        </div>
                                            
                                          
                                            
                                          </div>
                                            </div>
                                          
                                    </a>
                                    
                                       
                                            
                                    
                                    </div>
                                    
                                    
                                    <div class="col-sm-9 mail_view">
                                    <div class="inbox-body">
                                    <div class="mail_heading row">
                                    <div class="col-md-8">
                                    
                                    </div>
                                    <div class="col-md-4 text-right">
                                    
                                    </div>
                                    <div class="col-md-12">
                                    <h4> Daftar Barang Yang Ada Di Keranjang <small class="pull-right"><strong>Total Belanja : Rp {{number_format($sum,2,',','.')}}</strong> </small></h4>
                                    </div>
                                    </div>
                                    <ul class="messages">
                                            
                                            @foreach ($items as $item)
                                            <li>
                                                    <img src="{{asset('/storage/app/public/'.$item->gambar)}}" class="avatar" alt="Avatar">
                                                    <div class="message_date">
                                                    <h3 class="date text-info">Rp {{number_format($item->total,2,',','.')}}</h3>
                                                    <p class="month">Jumlah item {{$item->jumlah}} pcs</p>
                                                    <p class="month">@ Rp {{number_format($item->harga,2,',','.')}}
                                                    <br>
                                                    
                                                    </p>
                                                   
                                                    </div>
                                                    
                                                    <div class="message_wrapper">
                                                    <h4 class="heading">{{$item->nama_barang}}</h4>
                                                    <blockquote class="message">{{$item->description}}</blockquote>
                                                    <br />
                                                    
                                                           
                                                                            
                                                    
                                                                                    <button type="button" class="btn btn-default minus"><i class="fa fa-trash" style="color:red"></i> Hapus</button>
                                                                                    <button type="button" class="btn btn-default minus"><i class="fa fa-edit" style="color:darkorange"></i> Edit</button>
                                                                                    
                                                    </div>
                                                    </li>
                                            @endforeach
                                            
                                            </ul>
                                    </div>
                                    
                                    
                                    </div>
                                    </div>
                     
                    </div>

                  </div>
                  </div>
                </div>
          </div>
        </div>
        
        


@endsection

@push('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet" />

@endpush

@push('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>
<script>
$(document).ready(function() {
    $('.js-example-basic-single').select2();


    $.ajax({
        type: 'GET',
        url: '/ongkir/city',

        success: function(data) {


            
            var option = "";
            var html = '';
            for (i = 1; i < data.length; i++) {
                option = $('<option></option>').attr("value", data[i].city_id).text(data[i].city_name);


               
                $("#kota_tujuan").append(option);
            }


            //jika data berhasil didapatkan, tampilkan ke dalam option select kabupaten 

        }
    });

    $.ajax({
        type: 'GET',
        url: '/ongkir/city',

        success: function(data) {


            
            var option = "";
            var html = '';
            for (i = 1; i < data.length; i++) {
                option = $('<option></option>').attr("value", data[i].city_id).text(data[i].city_name);


                $("#kota_asal").append(option);
                
            }


            //jika data berhasil didapatkan, tampilkan ke dalam option select kabupaten 

        }
    });
    $.ajax({
        type: 'GET',
        url: '/ongkir/province',

        success: function(data) {


            console.log(data);
            var option = "";
            var html = '';
            for (i = 1; i < data.length; i++) {
                option = $('<option></option>').attr("value", data[i].province_id).text(data[i].province);


                $("#prov_tujuan").append(option);

            }


            //jika data berhasil didapatkan, tampilkan ke dalam option select kabupaten 

        }
    });
});
</script>
@endpush

resources/views/barang/edit.blade.php
@extends('layouts.master')

@section('content')


<div class="clearfix"></div>
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Edit
					<small>Barang</small>
				</h2>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<form action="{{route('barang.update',$data->id)}}" method="post" class="form-horizontal form-label-left"  enctype="multipart/form-data">
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}
                                  
					<div class="item form-group">
						<label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Kode barang 
							<span class="required"></span>
						</label>
						<div class="col-md-6 col-sm-6 col-xs-12">
							<input value="{{$data->kode_barang}}" readonly id="kd_barang" name="kd_barang" class="form-control col-md-7 col-xs-12"  type="text">
							</div>
						</div>
						<div class="item form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="name_barang">Nama barang 
								<span class="required"></span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<input value="{{$data->nama_barang}}" id="nama_barang" name="nama_barang" class="form-control col-md-7 col-xs-12"  type="text">
								</div>
							</div>
							<div class="item form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="stock_barang">Stock 
									<span class="required"></span>
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input value="{{$data->stock}}" id="stock_barang" name="stock_barang" class="form-control col-md-7 col-xs-12"  type="text">
									</div>
								</div>
								<div class="item form-group">
									<label class="control-label col-md-3 col-sm-3 col-xs-12" for="stock_barang">Harga 
										<span class="required"></span>
									</label>
									<div class="col-md-6 col-sm-6 col-xs-12">
										<input value="{{$data->harga}}" id="harga_barang" name="harga_barang" class="form-control col-md-7 col-xs-12"  type="text">
										</div>
									</div>
									<div class="item form-group">
										<label for="description" class="control-label col-md-3 col-sm-3 col-xs-12">Deskripsi</label>
										<div class="col-md-6 col-sm-6 col-xs-12">
											<textarea id="description" required="required" class="form-control" 
                                                                name="description" data-parsley-trigger="keyup" data-parsley-minlength="10" 
                                                                data-parsley-maxlength="50" 
                                                                data-parsley-minlength-message="Come on! You need to enter at least a 20 caracters long comment.." 
                                                                data-parsley-validation-threshold="10" placeholder="minimal 10 kata, maksimal 50 kata" required></textarea>
										</div>
									</div>
									<div class="item form-group">
										<label class="control-label col-md-3 col-sm-3 col-xs-12" for="stock_barang">Gambar 
											<span class="required"></span>
										</label>
										<div class="col-md-6 col-sm-6 col-xs-12">
											<img src="{{asset('storage/app/public/'.$data->gambar)}}" style="object-fit:contain;width:20%" >
												<br>
													<br>
														<input type="file" name="gambar_barang">
														</div>
													</div>
													<div class="ln_solid"></div>
													<div class="form-group">
														<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
															<button class="btn btn-danger" type="button">Cancel</button>
															<button class="btn btn-primary" type="submit">Update</button>
														</div>
													</form>
												</div>
											</div>
										</div>
									</div>
								</div>
        
          

@endsection

resources/views/barang/index.blade.php
@extends('layouts.master')

@section('content')

          <div class="clearfix"></div>
          <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="x_panel">
                    <div class="x_title">
                      <h2>Data<small>Barang</small></h2>
                      
                      <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                      <div style="overflow-x:auto">
                      <table id="datatable" class="table table-striped table-responsive">
                        <thead>
                          
                          <tr>
                            <th>Kode Barang</th>
                            <th>Nama Barang</th>
                            <th>Stock</th>
                            <th>Harga</th>
                            <th style="text-align:center">Gambar</th>
                            <th style="text-align:center">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                           @foreach($data as $d)
                            <tr>
                              <td>{{$d->kode_barang}}</td>
                              <td>{{$d->nama_barang}}</td>
                              <td>{{$d->stock}}</td>
                              <td>{{$d->harga}}</td>
                              <td style="width:5%;text-align:center"><img src="{{asset('storage/app/public/'.$d->gambar)}}" style="width:1cm;height:1cm
                              object-fit: contain; "></td>
                              <td style="text-align:center">
                                      <a href="{{route('barang.edit',$d->id)}}" class="btn btn-default btn-xs" style="color:darkorange"> <i class="fa fa-edit"></i> Edit</a>
                             
                                <form method="POST" action="{{route('barang.destroy',$d->id)}}">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button type="submit" class="btn btn-default btn-xs" style="color:red" onclick="return confirm('Are you sure?')"> <i class="fa fa-trash"> Hapus</i></button>
                                </form>    
                              </td>
                             
                            </tr>
                           @endforeach
                        </tbody>
                      </table>
                     
                    </div>
                    {{ $data->links() }}
                  </div>
                  </div>
                </div>
          </div>
        </div>
        
        <a href="#" class="float" data-toggle="modal" data-target="#barang">
                <i class="fa fa-plus my-float"></i>
                </a>
                <div class="label-container">
                <div class="label-text">Tambah Barang</div>
                <i class="fa fa-play label-arrow"></i>
                </div>

<!-- Modal -->
<div id="barang" class="modal fade" role="dialog">
        <div class="modal-dialog">
      
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              
            </div>
            <div class="modal-body">
            <form action="{{route('barang.store')}}" method="post" class="form-horizontal form-label-left"  enctype="multipart/form-data">
                  {{ csrf_field() }}
                    <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Kode barang <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              <input id="kd_barang" name="kd_barang" class="form-control col-md-7 col-xs-12" required="required" type="text">
                            </div>
                    </div>
                    <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name_barang">Nama barang <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              <input id="nama_barang" name="nama_barang" class="form-control col-md-7 col-xs-12" required="required" type="text">
                            </div>
                    </div>
                    <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="stock_barang">Stock <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              <input id="stock_barang" name="stock_barang" class="form-control col-md-7 col-xs-12" required="required" type="text">
                            </div>
                    </div>
                    <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="stock_barang">Harga <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              <input id="harga_barang" name="harga_barang" class="form-control col-md-7 col-xs-12" required="required" type="text">
                            </div>
                    </div>
                    <div class="item form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="stock_barang">Berat <span class="required">*</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="berat" name="berat" class="form-control col-md-7 col-xs-12" required="required" type="text">
                      </div>
              </div>
                    <div class="item form-group">
                        <label for="description" class="control-label col-md-3 col-sm-3 col-xs-12">Deskripsi</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <textarea id="description" required="required" class="form-control" 
                                                                    name="description" data-parsley-trigger="keyup" data-parsley-minlength="10" 
                                                                    data-parsley-maxlength="50" 
                                                                    data-parsley-minlength-message="Come on! You need to enter at least a 20 caracters long comment.." 
                                                                    data-parsley-validation-threshold="10" placeholder="minimal 10 kata, maksimal 50 kata" required></textarea>
                        </div>
                      </div>
                    <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="stock_barang">Gambar <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              <input id="gambar_barang" name="gambar_barang" class=" " required="required" type="file">
                            </div>
                    </div>
            </div>
            <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Cancel</button>
                    <button id="send" type="submit" class="btn btn-success">Submit</button>
                    
            </div>
          </div>
        </form>
        </div>
      </div>


@endsection

@push('css')
<link href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css" rel="stylesheet">

<style>
*{padding:0;margin:0;}

body{
	font-family:Verdana, Geneva, sans-serif;
	background-color:#CCC;
	font-size:12px;
}

.label-container{
	position:fixed;
	bottom:48px;
	right:105px;
	display:table;
	visibility: hidden;
}

.label-text{
	color:black;
	background:rgba(51,51,51,0.5);
	display:table-cell;
	vertical-align:middle;
	padding:10px;
	border-radius:3px;
}

.label-arrow{
	display:table-cell;
	vertical-align:middle;
	color:#333;
	opacity:0.5;
}

.float{
	position:fixed;
	width:60px;
	height:60px;
	bottom:30px;
	right:40px;
	background-color:#1ABB9C;
	color:#FFF;
	border-radius:50px;
	text-align:center;
	box-shadow: 2px 2px 3px #999;
}

.my-float{
	font-size:24px;
	margin-top:18px;
}

a.float + div.label-container {
  visibility: hidden;
  opacity: 0;
  transition: visibility 0s, opacity 0.5s ease;
}

a.float:hover + div.label-container{
  visibility: visible;
  opacity: 1;
}

</style>
@endpush

@push('js')

@endpush